"""Resolve metadata only, preserving existing pins, then bind torch to its official wheel."""
from pathlib import Path
import subprocess
import sys

ROOT=Path(__file__).resolve().parents[1]
TORCH_URL='https://download.pytorch.org/whl/cu126/torch-2.13.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl'
lock=ROOT/'requirements.lock'
scratch=ROOT/'work/requirements.resolved'
scratch.parent.mkdir(exist_ok=True)
# uv's direct-URL path may fetch a whole GPU wheel. Resolve via the explicitly
# scoped index in pyproject.toml instead, which supplies PEP 658 metadata.
scratch.write_text(lock.read_text().replace('torch @ '+TORCH_URL,'torch==2.13.0+cu126'),encoding='utf-8')
subprocess.run(['uv','pip','compile','pyproject.toml','--python-version','3.12',
    '--python-platform','x86_64-manylinux_2_28','--only-binary',':all:',
    '--generate-hashes','--quiet','--exclude-newer','2026-09-14T00:00:00Z',
    '--index-url','https://pypi.org/simple','-o',str(scratch)],cwd=ROOT,check=True)
text=scratch.read_text().replace('torch==2.13.0+cu126','torch @ '+TORCH_URL)
# Stable header independent of checkout path and generator environment.
text='\n'.join(line for line in text.splitlines() if not line.startswith('#'))+'\n'
lock.write_text('# Generated by scripts/lock_runtime.py; review dependency-audit.json before use.\n'+text,encoding='utf-8',newline='\n')
subprocess.run([sys.executable,str(ROOT/'scripts/audit_dependencies.py')],cwd=ROOT,check=True)
subprocess.run([sys.executable,str(ROOT/'scripts/sync_setup.py')],cwd=ROOT,check=True)
