"""Generate/check the CPU test lock and audit every artifact before installation.

No resolver runs here: all versions and hashes come from the reviewed runtime
lock. HTTPX is explicit because FastAPI's TestClient needs it at import time.
"""
import argparse
from datetime import datetime, timedelta, timezone
import json
from pathlib import Path
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = {
    "fastapi", "starlette", "uvicorn", "httpx", "httpcore", "anyio",
    "pydantic", "pydantic-core", "typing-extensions", "typing-inspection",
    "annotated-types", "annotated-doc", "idna", "certifi", "h11", "click",
}


def render():
    source = (ROOT / "requirements.lock").read_text(encoding="utf-8")
    blocks = re.split(r"\n(?=[a-z])", source)
    selected = {}
    for block in blocks:
        match = re.search(r"^([a-z0-9-]+)==([^\s]+)", block, re.M)
        if match and match[1] in PACKAGES:
            # Drop resolver comments; keep exact version and every artifact hash.
            selected[match[1]] = "\n".join(
                line for line in block.splitlines() if not line.lstrip().startswith("#")
            ).strip() + "\n"
    if selected.keys() != PACKAGES:
        raise RuntimeError("CPU test dependencies missing from runtime lock")
    return "# Generated by scripts/test_environment.py --write; do not resolve independently.\n" + "".join(
        selected[name] for name in sorted(selected)
    )


def audit(lock):
    cutoff = datetime.now(timezone.utc) - timedelta(hours=72)
    for block in re.split(r"\n(?=[a-z])", lock):
        match = re.search(r"^([a-z0-9-]+)==([^\s]+)", block, re.M)
        if not match:
            continue
        name, version = match.groups()
        url = f"https://pypi.org/pypi/{name}/{version}/json"
        with urllib.request.urlopen(url, timeout=30) as response:
            metadata = json.load(response)
        normalize = lambda value: re.sub(r"[-_.]+", "-", value).lower()
        if normalize(metadata["info"]["name"]) != name or metadata["info"]["version"] != version:
            raise RuntimeError(f"Registry identity mismatch: {name}")
        if metadata["vulnerabilities"]:
            raise RuntimeError(f"Published advisory for {name}=={version}")
        files = {item["digests"]["sha256"]: item for item in metadata["urls"]}
        hashes = re.findall(r"--hash=sha256:([0-9a-f]{64})", block)
        if not hashes:
            raise RuntimeError(f"Missing artifact integrity: {name}")
        for digest in hashes:
            item = files[digest]
            uploaded = datetime.fromisoformat(item["upload_time_iso_8601"].replace("Z", "+00:00"))
            if item["yanked"] or uploaded > cutoff or not item["url"].startswith("https://files.pythonhosted.org/"):
                raise RuntimeError(f"Unreviewable artifact: {name} {item['filename']}")
        print(f"Verified {name}=={version}: {len(hashes)} registry hashes, age >=72h; {url}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--audit", action="store_true")
    args = parser.parse_args()
    expected = render()
    path = ROOT / "requirements-test.lock"
    if args.write:
        path.write_text(expected, encoding="utf-8", newline="\n")
    elif path.read_text(encoding="utf-8") != expected:
        raise RuntimeError("Test lock drift; run scripts/test_environment.py --write and review")
    if args.audit:
        audit(expected)


if __name__ == "__main__":
    main()
